build::
	cabal build
	mkdir -p out
	./dist/build/cufp-metaprogramming-tutorial-slides/cufp-metaprogramming-tutorial-slides

clean::
	cabal clean

configure::
	cabal configure

rebuild:: clean configure build
