_build/JsonComprehension.cmo:
	ocamlbuild JsonComprehension.cmo

install:
	ocamlfind install json_compr META _build/JsonComprehension.cmo

uninstall:
	ocamlfind remove json_compr

clean:
	ocamlbuild -clean

.PHONY: _build/JsonComprehension.cmo
